apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: producer-release-remote-v2
  namespace: default
spec:
  values:
    invocationMode: INSTALL
    app:
      version: 1.2.3
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: producer-remote
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: ack-git
      interval: 5m
  releaseName: producer-release-remote-v2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  kubeConfig:
    secretRef:
      name: tf-remote-kubeconfig-secret