
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: remote-kubeconfig-reader
  namespace: default
spec:
  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: terraform/read-remote-kubeconfig
  runnerPodTemplate:
    spec:
      image: 810918108393.dkr.ecr.eu-south-1.amazonaws.com/tf-runner-tools:v1

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: ack-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa

  # Terraform variables (match your variables.tf)
  vars:
    - name: region
      value: "eu-south-1"
    - name: eks_cluster_name
      value: "k8-simulation-client"

  # (Optional) Inject env vars from Secret (AWS creds)
  varsFrom:
    - kind: Secret
      name: aws-creds
